// ==============================================
// Copyright (c) 2025 reall3d.com, MIT license
// ==============================================
import { data190To19, data10190To10019, sh123To1, sh123To2, sh123To3, webpToRgba, data220Decode, decodeWebpBlockDatas } from '../../utils/CommonUtils';
import {
    SplatDataSize16,
    SplatDataSize32,
    SpxBlockFormatData190,
    SpxBlockFormatData10190,
    SpxBlockFormatSH1,
    SpxBlockFormatSH2,
    SpxBlockFormatSH3,
    SpxBlockFormatSH4,
    WasmBlockSize,
    SpxBlockFormatSH8,
    SpxBlockFormatSH9,
    SpxBlockFormatData220,
    SpxBlockFormatData230,
} from '../../utils/consts/GlobalConstants';
import { SpxHeader } from '../ModelData';

const WasmDataV1 = `AGFzbQEAAAAADwhkeWxpbmsuMAEEAAAAAAEeBmABfQF9YAAAYAJ/fwF/YAF9AX9gAX8Bf2ACf38AAhoCA2VudgRleHBmAAADZW52Bm1lbW9yeQIAAAMGBQECAwQFByEEEV9fd2FzbV9jYWxsX2N0b3JzAAEBSAAEAXcABQFEAAIKhAsFAwABC6MJAyh/Dn0EfCABKAIEQYvwCUcEQEEBDwsgASgCACIEQQBMBEBBAA8LIAFBCWoiAiAEQRNsaiEHIAIgBEESbGohCCACIARBEWxqIQkgAiAEQQR0aiEKIAIgBEEPbGohCyACIARBDmxqIQwgAiAEQQ1saiENIAIgBEEMbGohDiACIARBC2xqIQ8gAiAEQQpsaiEQIAIgBEEJbGohESACIARBBmxqIRIgAiAEQQNsaiETQQAhAiABLQAIIRQDQCACIAhqLQAAIRUgAiAJai0AACEWIAIgCmotAAAhFyACIAtqLQAAIRggAiAMai0AACEZIAIgDWotAAAhGiACIA5qLQAAIRsgAiAPai0AACEcIAIgEGotAAAhHSACIBFqLQAAIR4gEiACQQNsIgNqIgUtAAAhHyADIBNqIgYtAAAhICABIANqIgMtAAohISADLQAJISIgBS0AASEjIAYtAAEhJCADLQALIiXAISYgBS0AAiInwCEoIAYtAAIiBsAhKUEAIQUgFARAIAcgAkEBdGoiAy0AASIFQQh0QYD+AXEgAy0AAHIgBUEJdEGAgARxciEFCyAAIAJBBXRqIgMgBTYCDCADICNBCHQgH3IgJ0EQdHIiBUGAgIB4ciAFIChBAEgbskMAAIA5lDgCCCADICRBCHQgIHIgBkEQdHIiBUGAgIB4ciAFIClBAEgbskMAAIA5lDgCBCADICFBCHQgInIgJUEQdHIiBUGAgIB4ciAFICZBAEgbskMAAIA5lDgCACAcs0MAAIA9lEMAACDBkhAAIS8gHbNDAACAPZRDAAAgwZIQACExIAMgF7NDAAAAw5JDAAAAPJQiKyAVs0MAAADDkkMAAAA8lCItIC2UIiogFrNDAAAAw5JDAAAAPJQiLiAulCIsQwAAAABDAACAPyAqICwgKyArlCIrkpKTIiqRICpDAAAAAF0bIiwgLJQgK5KSkpEiKpUiKyAtICqVIi2UIjMgLCAqlSIwIC4gKpUiKpQiNJK7IjggOKAgL7siOKK2Ii4gLpREAAAAAAAA8D8gKiAqlCI1IC0gLZQiNpK7IjogOqChIB6zQwAAgD2UQwAAIMGSEAC7IjqitiIsICyUICsgKpQiMiAwIC2UIjeTuyI7IDugIDG7IjuitiIvIC+UkpJDAACAQJQQAyAuICogLZQiMSAwICuUIjCTuyI5IDmgIDiitiItlCAsIDIgN5K7IjkgOaAgOqK2IiqUIC9EAAAAAAAA8D8gKyArlCIyIDaSuyI5IDmgoSA7orYiK5SSkkMAAIBAlBADQRB0cjYCECADIC5EAAAAAAAA8D8gMiA1krsiOSA5oKEgOKK2Ii6UICwgMyA0k7siOCA4oCA6orYiLJQgLyAxIDCSuyI4IDigIDuitiIvlJKSQwAAgECUEAMgLSAtlCAqICqUICsgK5SSkkMAAIBAlBADQRB0cjYCFCADIBpBCHQgG3IgGUEQdHIgGEEYdHI2AhwgAyAtIC6UICogLJQgKyAvlJKSQwAAgECUEAMgLiAulCAsICyUIC8gL5SSkkMAAIBAlBADQRB0cjYCGCACQQFqIgIgBEcNAAtBAAtyAQR/IAC8IgRB////A3EhAQJAIARBF3ZB/wFxIgJFDQAgAkHwAE0EQCABQYCAgARyQfEAIAJrdiEBDAELIAJBjQFLBEBBgPgBIQNBACEBDAELIAJBCnRBgIAHayEDCyADIARBEHZBgIACcXIgAUENdnILMgECf0HBphYhAQNAIAAgAmotAAAgAUEhbHMhASACQQFqIgJB/ABHDQALIAEgACgCfEcLMwAgAEEIQQQgAUEBRhtqQQA2AgAgAEEANgAcIAD9DAAAAQCMERYAlQFsEu2BMhP9CwIMCw==`;
const WasmDataV2 = `AGFzbQEAAAAADwhkeWxpbmsuMAEEAAAAAAEeBmABfQF9YAAAYAJ/fwF/YAF9AX9gAX8Bf2ACf38AAhoCA2VudgRleHBmAAADZW52Bm1lbW9yeQIAAAMGBQECAwQFByEEEV9fd2FzbV9jYWxsX2N0b3JzAAEBSAAEAXcABQFEAAIK3gwFAwABC+wKAy1/Dn0EfCABKAIEQfiuDUcEQEEBDwsgASgCACICQQBKBEAgAUEJaiIDIAJBE2xqIQcgAyACQRJsaiEIIAMgAkERbGohCSADIAJBD2xqIQogAyACQQ5saiELIAMgAkENbGohDCADIAJBDGxqIQ0gAyACQQtsaiEOIAMgAkEKbGohDyADIAJBCWxqIRAgAyACQQN0aiERIAMgAkEHbGohEiADIAJBBmxqIRMgAyACQQVsaiEUIAMgAkECdGohFSADIAJBA2xqIRYgAyACQQF0aiEXIAEgAmpBCWohGCABIAJBBHRqQQlqIRkgAS0ACCEaQQAhAQNAIAEgFGotAAAhBCABIBVqLQAAIRsgASAWai0AACEcIAEgF2otAAAhHSABIBhqLQAAIR4gASADai0AACEfIAEgEWotAAAiIMAhISABIBJqLQAAIiLAISMgASATai0AACIkwCElQQAhBSAaBEAgByABQQF0aiIFLQABIgZBCHRBgP4BcSAFLQAAciAGQQl0QYCABHFyIQULIAEgCGotAAAhBiABIAlqLQAAISYgASAZai0AACEnIAEgCmotAAAhKCABIAtqLQAAISkgASAMai0AACEqIAEgDWotAAAhKyABIA5qLQAAISwgASAPai0AACEtIAEgEGotAAAhLiAEQQh0IB1yICBBEHRyIgRBgICAeHIgBCAhQQBIG7IhMiAbQQh0IB5yICJBEHRyIgRBgICAeHIgBCAjQQBIG7JDAACAOZQhMAJ9IBxBCHQgH3IgJEEQdHIiBEGAgIB4ciAEICVBAEgbskMAAIA5lCIvQwAAAABdBEAgL4wQAEMAAIC/kowMAQsgLxAAQwAAgL+SCyExIDJDAACAOZQhLwJ9IDBDAAAAAF0EQCAwjBAAQwAAgL+SjAwBCyAwEABDAACAv5ILITACfSAvQwAAAABdBEAgL4wQAEMAAIC/kowMAQsgLxAAQwAAgL+SCyEvIAAgAUEFdGoiBCAxOAIAIAQgBTYCDCAEIC84AgggBCAwOAIEICyzQwAAgD2UQwAAIMGSEAAhNCAts0MAAIA9lEMAACDBkhAAITYgBCAns0MAAADDkkMAAAA8lCIwIAazQwAAAMOSQwAAADyUIi8gL5QiMSAms0MAAADDkkMAAAA8lCIyIDKUIjNDAAAAAEMAAIA/IDEgMyAwIDCUIjCSkpMiMZEgMUMAAAAAXRsiMyAzlCAwkpKSkSIxlSIwIC8gMZUiL5QiOCAzIDGVIjUgMiAxlSIxlCI5krsiPSA9oCA0uyI9orYiMiAylEQAAAAAAADwPyAxIDGUIjogLyAvlCI7krsiPyA/oKEgLrNDAACAPZRDAAAgwZIQALsiP6K2IjMgM5QgMCAxlCI3IDUgL5QiPJO7IkAgQKAgNrsiQKK2IjQgNJSSkkMAAIBAlBADIDIgMSAvlCI2IDUgMJQiNZO7Ij4gPqAgPaK2Ii+UIDMgNyA8krsiPiA+oCA/orYiMZQgNEQAAAAAAADwPyAwIDCUIjcgO5K7Ij4gPqChIECitiIwlJKSQwAAgECUEANBEHRyNgIQIAQgMkQAAAAAAADwPyA3IDqSuyI+ID6goSA9orYiMpQgMyA4IDmTuyI9ID2gID+itiIzlCA0IDYgNZK7Ij0gPaAgQKK2IjSUkpJDAACAQJQQAyAvIC+UIDEgMZQgMCAwlJKSQwAAgECUEANBEHRyNgIUIAQgKkEIdCArciApQRB0ciAoQRh0cjYCHCAEIC8gMpQgMSAzlCAwIDSUkpJDAACAQJQQAyAyIDKUIDMgM5QgNCA0lJKSQwAAgECUEANBEHRyNgIYIAFBAWoiASACRw0ACwtBAAtyAQR/IAC8IgRB////A3EhAQJAIARBF3ZB/wFxIgJFDQAgAkHwAE0EQCABQYCAgARyQfEAIAJrdiEBDAELIAJBjQFLBEBBgPgBIQNBACEBDAELIAJBCnRBgIAHayEDCyADIARBEHZBgIACcXIgAUENdnILQwECf0GVowNBwaYWIAAoAjBBx92XvQRGGyEBA0AgACACai0AACABQSFscyEBIAJBAWoiAkH8AEcNAAsgASAAKAJ8RwszACAAQQhBBCABQQFGG2pBADYCACAAQQA2ABwgAP0MAAABAIwRFgCVAWwS7YEyE/0LAgwL`;
const WasmDataV3 = `AGFzbQEAAAAADwhkeWxpbmsuMAEEAAAAAAE3CGAEf39/fwBgAX0BfWAAAGADf39/AX9gAX8Bf2ACf38AYA5/f319fX19fX19fX1/fwBgAX0BfwIaAgNlbnYEZXhwZgABA2VudgZtZW1vcnkCAAADCQgCAwAABAUGBwchBBFfX3dhc21fY2FsbF9jdG9ycwABAUgABQF3AAYBRAACCsAWCAMAAQtqAQF/An8CQAJAAkAgASgCBCIDQfanEmsOAgECAAsgA0HIqRJHBEBBASADQb6pEkcNAxogACABIAJBARADQQAPCyAAIAEgAkEAEANBAA8LIAAgASACQQEQBEEADwsgACABIAJBABAEQQALC5YIAwt9AnscfyABKAIAIhFBAEoEQCARQRhsQQhqIRsgEUEUbEEIaiEcIBFBBHRBCHIhHSARQQxsQQhqIR4gEUEDdEEIaiEfIBFBAnRBCGohIEEcQRggAS0ACyIhQf4BRhsgEWxBCGohIiACQQBMISMDQCABIBdBAnQiAiAcamohEiABIAIgHmpqIRMgASACIB9qaiIYLQAAIRQgGC8AASEYIAEgAmoiGS8ACf0Q/YkBIQ8gASACICBqaiIaLwAB/RD9iQEhECAhQf4BRgRAIBMtAANB/wFzIAEgAiAbamoiFi0AAEEBdHIgFi0AAUEJdHIhFgsgGS0ACCEZIBotAAAhGiAjRQRAIAEgAiAiamoiFS0AAUEIdCAVLQAAciEVCyASLQAAISQgASACIB1qaiICLQAAISUgEy0AACEmIBItAAMhJyASLQACISggEi0AASESIAItAAMhKSACLQACISogAi0AASErIBMtAAIhLCATLQABIRMgGkEIdCAZciAUQRB0ciICQYCAgHhyIAIgFMBBAEgbskMAAIA5lCEGIBD9qQFBCP2rASAP/akB/VAgGP0QIg/9iQH9qQFBEP2rAf1QIhD9DAAAAP8AAAD/AAAA/wAAAP/9UCAQIA/9DAAAAAAAAAAAAAAAAAAAAAD9Jf2HAf2nAf1S/foB/QwAAIA5AACAOQAAgDkAAIA5/eYBIQ8gAwRAAn0gBkMAAAAAXQRAIAaMEABDAACAv5KMDAELIAYQAEMAAIC/kgshBiAP/R8AIQQgAyECA0ACfSAEQwAAAABdBEAgBIwQAEMAAIC/kowMAQsgBBAAQwAAgL+SCyEEIAJBAUchFCACQQFrIQIgFA0ACyAP/R8BIQUgAyECA0ACfSAFQwAAAABdBEAgBYwQAEMAAIC/kowMAQsgBRAAQwAAgL+SCyEFIAJBAUchFCACQQFrIQIgFA0ACyAE/RMgBf0gASEPCyArQQh0ICVyICpBEHRyIClBGHRyIQIgLLNDAACAPZRDAAAgwZIQACEMIBOzQwAAgD2UQwAAIMGSEAAhDSAms0MAAIA9lEMAACDBkhAAIQ5DAAAAAEMAAIA/ICizQwAAf0OVQwAAAL+SQ/MEtT+UIgUgBZQgJLNDAAB/Q5VDAAAAv5JD8wS1P5QiBCAElCASs0MAAH9DlUMAAAC/kkPzBLU/lCIIIAiUkpKTIgeRIAdDAAAAAF0bIgshCSAFIQcgCCEKAkACfQJAAkACQCAnQfwBaw4DBAABAgsgBCEJIAshBAwDCyAEIQkgCyEKIAUMAQsgBCEJIAUhCiALCyEHIAghBAsgACAXQQN0IAYgD/0fACAP/R8BIA4gDSAMIAkgBCAKIAcgAiAVIBZBEHRyEAcgF0EBaiIXIBFHDQALCwvgBwIwfwN9IAEoAgAiBEEASgRAIAFBCWoiBSAEQRVsaiELIAUgBEEUbGohDCAFIARBE2xqIQ0gBSAEQRJsaiEOIAUgBEERbGohDyAFIARBD2xqIRAgBSAEQQ5saiERIAUgBEENbGohEiAFIARBDGxqIRMgBSAEQQtsaiEUIAUgBEEKbGohFSAFIARBCWxqIRYgBSAEQQN0aiEXIAUgBEEHbGohGCAFIARBBmxqIRkgBSAEQQVsaiEaIAUgBEECdGohGyAFIARBA2xqIRwgBSAEQQF0aiEdIAEgBGpBCWohHiABIARBBHRqQQlqIR8gBUEWQRQgAS0ACCIgGyAEbGoiISAEaiEiIAJBAEwhI0EAIQIDQCACIBdqLQAAIQEgAiAYai0AACEGIAIgGWotAAAhCiAgBEAgAiAMai0AACACIAtqLQAAQQh0ciEICyACIBpqLQAAIQkgAiAbai0AACEkIAIgHGotAAAhJSACIB1qLQAAISYgAiAeai0AACEnIAIgBWotAAAhKCAjRQRAIAIgIWotAAAgAiAiai0AAEEIdHIhBwsgAiANai0AACEpIAIgDmotAAAhKiACIA9qLQAAISsgAiAfai0AACEsIAIgEGotAAAhLSACIBFqLQAAIS4gAiASai0AACEvIAIgE2otAAAhMCACIBRqLQAAITEgAiAVai0AACEyIAIgFmotAAAhMyAJQQh0ICZyIAFBEHRyIglBgICAeHIgCSABwEEASBuyQwAAgDmUITQgJEEIdCAnciAGQRB0ciIBQYCAgHhyIAEgBsBBAEgbskMAAIA5lCE1ICVBCHQgKHIgCkEQdHIiAUGAgIB4ciABIArAQQBIG7JDAACAOZQhNiADBEACfSA2QwAAAABdBEAgNowQAEMAAIC/kowMAQsgNhAAQwAAgL+SCyE2IAMhAQNAAn0gNUMAAAAAXQRAIDWMEABDAACAv5KMDAELIDUQAEMAAIC/kgshNSABQQFHIQYgAUEBayEBIAYNAAsgAyEBA0ACfSA0QwAAAABdBEAgNIwQAEMAAIC/kowMAQsgNBAAQwAAgL+SCyE0IAFBAUchBiABQQFrIQEgBg0ACwsgACACQQN0IDYgNSA0IDOzQwAAgD2UQwAAIMGSEAAgMrNDAACAPZRDAAAgwZIQACAxs0MAAIA9lEMAACDBkhAAICyzQwAAAMOSQwAAADyUICuzQwAAAMOSQwAAADyUICqzQwAAAMOSQwAAADyUICmzQwAAAMOSQwAAADyUIC9BCHQgMHIgLkEQdHIgLUEYdHIgByAIQRB0chAHIAJBAWoiAiAERw0ACwsLQwECf0GVowNBwaYWIAAoAjBBx92XvQRGGyEBA0AgACACai0AACABQSFscyEBIAJBAWoiAkH8AEcNAAsgASAAKAJ8RwszACAAQQhBBCABQQFGG2pBADYCACAAQQA2ABwgAP0MAAABAIwRFgCVAWwS7YEyE/0LAgwL6QMCBHwEfSAAIAFBAnRqIgAgAjgCACAAIA02AgwgACAEOAIIIAAgAzgCBCAAIAkgCyALlCAKIAqUIAggCJQgCSAJlJKSkpEiBJUiAiALIASVIgOUIgkgCCAElSIIIAogBJUiBJQiCpK7Ig4gDqAgB7siDqK2IgcgB5REAAAAAAAA8D8gBCAElCILIAMgA5QiE5K7IhAgEKChIAW7IhCitiIFIAWUIAIgBJQiEiAIIAOUIhSTuyIRIBGgIAa7IhGitiIGIAaUkpJDAACAQJQQCCAHIAQgA5QiFSAIIAKUIgiTuyIPIA+gIA6itiIDlCAFIBIgFJK7Ig8gD6AgEKK2IgSUIAZEAAAAAAAA8D8gAiAClCISIBOSuyIPIA+goSARorYiApSSkkMAAIBAlBAIQRB0cjYCECAAIAdEAAAAAAAA8D8gEiALkrsiDyAPoKEgDqK2IgeUIAUgCSAKk7siDiAOoCAQorYiBZQgBiAVIAiSuyIOIA6gIBGitiIGlJKSQwAAgECUEAggAyADlCAEIASUIAIgApSSkkMAAIBAlBAIQRB0cjYCFCAAIAw2AhwgACADIAeUIAQgBZQgAiAGlJKSQwAAgECUEAggByAHlCAFIAWUIAYgBpSSkkMAAIBAlBAIQRB0cjYCGAtyAQR/IAC8IgRB////A3EhAQJAIARBF3ZB/wFxIgJFDQAgAkHwAE0EQCABQYCAgARyQfEAIAJrdiEBDAELIAJBjQFLBEBBgPgBIQNBACEBDAELIAJBCnRBgIAHayEDCyADIARBEHZBgIACcXIgAUENdnIL`;
const WasmOpen = `AGFzbQEAAAAADwhkeWxpbmsuMAEEAAAAAAE+CWAEf39/fwBgAX0BfWAAAGADf39/AX9gA39/fwBgDn9/fX19fX19fX19fX9/AGABfwF/YAJ/fwF/YAF9AX8CGgIDZW52BGV4cGYAAQNlbnYGbWVtb3J5AgAAAwoJAgMAAAQFBgcIByEEEV9fd2FzbV9jYWxsX2N0b3JzAAEBSAAHAXMACAFEAAIKxCwJAwABC+YPARx/QQEhDwJAAkACQAJAAkACQAJAAkACQAJAAkAgASgCBCIDQdsBTARAAkAgA0ETaw4FBQYMAgMACyADQQFrDgMICQoLCyADQaPOAEYNAiADQeYBRwRAIANB3AFHDQsgACABIAJBARADDAYLIAAgASACQQAQA0EADwsgACABIAJBARAEDAQLIAAgASACQQAQBEEADwsgACABQQwQBQwCCyAAIAFBCBAFDAELIAEoAgAiA0EASg0BC0EADwsgAUEIaiICIANBE2xqIQUgAiADQRJsaiEGIAIgA0ERbGohCCACIANBBHRqIQkgAiADQQ9saiEKIAIgA0EObGohCyACIANBDWxqIQwgAiADQQxsaiENIAIgA0ELbGohDiACIANBCmxqIRAgAiADQQlsaiERIAIgA0EGbGohEiACIANBA2xqIRNBACEPQQAhAgNAIAIgDGotAAAhFCACIA1qLQAAIRUgAiALai0AACEWIAIgCmotAAAhFyACIAVqLQAAIRggAiAGai0AACEZIAIgCGotAAAhGiACIAlqLQAAIRwgAiAOai0AACEdIAIgEGotAAAhHiAAIAJBA3QgASACQQNsIgRqIgcvAAggBywACiIHQf8BcUEQdHIiG0GAgIB4ciAbIAdBAEgbskMAAIA5lCAEIBNqIgcvAAAgBywAAiIHQf8BcUEQdHIiG0GAgIB4ciAbIAdBAEgbskMAAIA5lCAEIBJqIgQvAAAgBCwAAiIEQf8BcUEQdHIiB0GAgIB4ciAHIARBAEgbskMAAIA5lCACIBFqLQAAs0MAAIA9lEMAACDBkhAAIB6zQwAAgD2UQwAAIMGSEAAgHbNDAACAPZRDAAAgwZIQACAcuEQAAAAAAABgwKBEAAAAAAAAgD+itiAauEQAAAAAAABgwKBEAAAAAAAAgD+itiAZuEQAAAAAAABgwKBEAAAAAAAAgD+itiAYuEQAAAAAAABgwKBEAAAAAAAAgD+itiAVIBRBCHRyIBZBEHRyIBdBGHRyQQAQBiACQQFqIgIgA0cNAAsMAwtBACEPIAEoAgAiBUEATA0CQQAhAgNAIAEgAkEJbGoiAy0ADSEGIAMtAAwhCCADLQALIQkgAy0ACiEKIAMtAAkhCyADLQAIIQwgAy0AECENIAMtAA8hDiADLQAOIQMgACACQQR0aiIEQoCAgIAQNwIIIAQgDUEQdEGAgOAHcSAOQRV0QYCAgPgBcSADQRp0QYCAgIB+cXJyNgIEIAQgBkEBdkH8AHEgCEEEdEGAH3EgCUEJdEGA4AdxIApBDnRBgID4AXEgC0ETdEGAgIA+cSAMQRh0QYCAgEBxcnJycnIgA0EGdnI2AgAgAkEBaiICIAVHDQALDAILQQAhDyABKAIAIghBAEwNAUEAIQIDQCABIAJBGGxqIgMtABohCSADLQAZIQogAy0AGCELIAMtABchDCADLQAWIQ0gAy0AFSEOIAMtAA0hECADLQAMIREgAy0ACyESIAMtAAohEyADLQAJIRQgAy0ACCEVIAMtABQhBSADLQATIRYgAy0AEiEXIAMtABEhGCADLQAQIRkgAy0ADyEaIAMtAA4hBiAAIAJBBHRqIgQgAy0AH0EFdEGAPnEgAy0AHkEKdEGAwA9xIAMtAB1BD3RBgIDwA3EgAy0AHEEUdEGAgID8AHEgAy0AGyIDQRl0QYCAgIB/cXJycnJBAXI2AgwgBCAWQQF0QfADcSAXQQZ0QYD8AHEgGEELdEGAgB9xIBlBEHRBgIDgB3EgGkEVdEGAgID4AXEgBkEadEGAgICAfnFycnJyciAFQQR2cjYCBCAEIBBBAXZB/ABxIBFBBHRBgB9xIBJBCXRBgOAHcSATQQ50QYCA+AFxIBRBE3RBgICAPnEgFUEYdEGAgIBAcXJycnJyIAZBBnZyNgIAIAQgCUECdkE+cSAKQQN0QcAPcSALQQh0QYDwA3EgDEENdEGAgPwAcSANQRJ0QYCAgB9xIA5BF3RBgICA4AdxIAVBHHRBgICAgHhxcnJycnJyIANBB3ZyNgIIIAJBAWoiAiAIRw0ACwwBC0EAIQ8gASgCACIIQQBMDQBBACECA0AgASACQRVsaiIDLQAaIQkgAy0AGSEKIAMtABghCyADLQAXIQwgAy0AFiENIAMtABUhDiADLQANIRAgAy0ADCERIAMtAAshEiADLQAKIRMgAy0ACSEUIAMtAAghFSADLQAUIQUgAy0AEyEWIAMtABIhFyADLQARIRggAy0AECEZIAMtAA8hGiADLQAOIQYgACACQQR0aiIEIAMtABxBFHRBgICA/ABxIAMtABsiA0EZdEGAgICAf3FyQQFyNgIMIAQgFkEBdEHwA3EgF0EGdEGA/ABxIBhBC3RBgIAfcSAZQRB0QYCA4AdxIBpBFXRBgICA+AFxIAZBGnRBgICAgH5xcnJycnIgBUEEdnI2AgQgBCAQQQF2QfwAcSARQQR0QYAfcSASQQl0QYDgB3EgE0EOdEGAgPgBcSAUQRN0QYCAgD5xIBVBGHRBgICAQHFycnJyciAGQQZ2cjYCACAEIAlBAnZBPnEgCkEDdEHAD3EgC0EIdEGA8ANxIAxBDXRBgID8AHEgDUESdEGAgIAfcSAOQRd0QYCAgOAHcSAFQRx0QYCAgIB4cXJycnJyciADQQd2cjYCCCACQQFqIgIgCEcNAAsLIA8LzAcDC30Dexl/IAEoAgAiEkEASgRAIBJBGGxBCGohHCASQRRsQQhqIR0gEkEEdEEIciEeIBJBDGxBCGohHyASQQN0QQhqISAgEkECdEEIaiEhIAJBAEwhIgNAIAEgF0ECdCICaiIZLQAIIRUgASACICFqaiIaLQAAISMgASACIB1qaiETIAEgAiAeamohFCABIAIgH2pqIRYgASACICBqaiIbLQAAIiTAISUgGy8AAf0QIQ8gGS8ACf0Q/YkB/akBIRAgGi8AAf0Q/YkB/akBIREgIkUEQCABIAIgHGpqIgItAAFBCHQgAi0AAHIhGAsgEy0AACEZIBQtAAAhGiAWLQAAIRsgEy0AAyEmIBMtAAIhJyATLQABIRMgFC0AAyEoIBQtAAIhKSAULQABIRQgFi0AAiEqIBYtAAEhFiAjQQh0IBVyICRBEHRyIgJBgICAeHIgAiAlQQBIG7JDAACAOZQhBiARQQj9qwEgEP1QIA/9iQH9qQFBEP2rAf1QIhD9DAAAAP8AAAD/AAAA/wAAAP/9UCAQIA/9DAAAAAAAAAAAAAAAAAAAAAD9Jf2HAf2nAf1S/foB/QwAAIA5AACAOQAAgDkAAIA5/eYBIQ8gAwRAAn0gBkMAAAAAXQRAIAaMEABDAACAv5KMDAELIAYQAEMAAIC/kgshBiAP/R8AIQQgAyECA0ACfSAEQwAAAABdBEAgBIwQAEMAAIC/kowMAQsgBBAAQwAAgL+SCyEEIAJBAUchFSACQQFrIQIgFQ0ACyAP/R8BIQUgAyECA0ACfSAFQwAAAABdBEAgBYwQAEMAAIC/kowMAQsgBRAAQwAAgL+SCyEFIAJBAUchFSACQQFrIQIgFQ0ACyAE/RMgBf0gASEPCyAUQQh0IBpyIClBEHRyIChBGHRyIQIgKrNDAACAPZRDAAAgwZIQACEMIBazQwAAgD2UQwAAIMGSEAAhDSAbs0MAAIA9lEMAACDBkhAAIQ5DAAAAAEMAAIA/ICezQwAAf0OVQwAAAL+SQ/MEtT+UIgUgBZQgGbNDAAB/Q5VDAAAAv5JD8wS1P5QiBCAElCATs0MAAH9DlUMAAAC/kkPzBLU/lCIIIAiUkpKTIgeRIAdDAAAAAF0bIgshCSAFIQcgCCEKAkACfQJAAkACQCAmQfwBaw4DBAABAgsgBCEJIAshBAwDCyAEIQkgCyEKIAUMAQsgBCEJIAUhCiALCyEHIAghBAsgACAXQQN0IAYgD/0fACAP/R8BIA4gDSAMIAkgBCAKIAcgAiAYEAYgF0EBaiIXIBJHDQALCwusBwIvfwN9IAEoAgAiBEEASgRAIAFBCGoiBSAEQRVsaiEIIAUgBEEUbGohCSAFIARBE2xqIQogBSAEQRJsaiELIAUgBEERbGohDCAFIARBD2xqIQ0gBSAEQQ5saiEOIAUgBEENbGohDyAFIARBDGxqIRAgBSAEQQtsaiERIAUgBEEKbGohEiAFIARBCWxqIRMgBSAEQQN0aiEUIAUgBEEHbGohFSAFIARBBmxqIRYgBSAEQQVsaiEXIAUgBEECdGohGCAFIARBA2xqIRkgBSAEQQF0aiEaIAEgBGpBCGohGyABIARBBHRqQQhqIRwgAkEATCEdQQAhAgNAIAIgF2otAAAhASACIBhqLQAAIQYgAiAZai0AACEeIAIgGmotAAAhHyACIBtqLQAAISAgAiAFai0AACEhIAIgFGotAAAiIsAhIyACIBVqLQAAIiTAISUgAiAWai0AACImwCEnIB1FBEAgAiAJai0AACACIAhqLQAAQQh0ciEHCyACIApqLQAAISggAiALai0AACEpIAIgDGotAAAhKiACIBxqLQAAISsgAiANai0AACEsIAIgDmotAAAhLSACIA9qLQAAIS4gAiAQai0AACEvIAIgEWotAAAhMCACIBJqLQAAITEgAiATai0AACEyIAFBCHQgH3IgIkEQdHIiAUGAgIB4ciABICNBAEgbskMAAIA5lCEzIAZBCHQgIHIgJEEQdHIiAUGAgIB4ciABICVBAEgbskMAAIA5lCE0IB5BCHQgIXIgJkEQdHIiAUGAgIB4ciABICdBAEgbskMAAIA5lCE1IAMEQAJ9IDVDAAAAAF0EQCA1jBAAQwAAgL+SjAwBCyA1EABDAACAv5ILITUgAyEBA0ACfSA0QwAAAABdBEAgNIwQAEMAAIC/kowMAQsgNBAAQwAAgL+SCyE0IAFBAUchBiABQQFrIQEgBg0ACyADIQEDQAJ9IDNDAAAAAF0EQCAzjBAAQwAAgL+SjAwBCyAzEABDAACAv5ILITMgAUEBRyEGIAFBAWshASAGDQALCyAAIAJBA3QgNSA0IDMgMrNDAACAPZRDAAAgwZIQACAxs0MAAIA9lEMAACDBkhAAIDCzQwAAgD2UQwAAIMGSEAAgK7NDAAAAw5JDAAAAPJQgKrNDAAAAw5JDAAAAPJQgKbNDAAAAw5JDAAAAPJQgKLNDAAAAw5JDAAAAPJQgLkEIdCAvciAtQRB0ciAsQRh0ciAHEAYgAkEBaiICIARHDQALCwuHBwIgfwR9IAEoAgAhAyACQQxGBEAgAS0ACCEGCyADQQBKBEAgASACaiIEIANBEmxqIQggBCADQRFsaiEJIAQgA0EEdGohCiAEIANBD2xqIQsgBCADQQ5saiEMIAQgA0ENbGohDSAEIANBDGxqIQ4gBCADQQtsaiEPIAQgA0EKbGohECAEIANBCWxqIREgBCADQQN0aiESIAQgA0EHbGohEyAEIANBBmxqIRQgBCADQQVsaiEVIAQgA0ECdGohFiAEIANBA2xqIRcgBCADQQF0aiEYIAMgBGohGUEAIQIDQCACIBhqLQAAIAIgFWotAABBCHRyIAIgEmosAAAiAUH/AXFBEHRyIgVBgICAeHIgBSABQQBIG7JDAACAOZQhIyACIBlqLQAAIAIgFmotAABBCHRyIAIgE2osAAAiAUH/AXFBEHRyIgVBgICAeHIgBSABQQBIG7JDAACAOZQhJCACIARqLQAAIAIgF2otAABBCHRyIAIgFGosAAAiAUH/AXFBEHRyIgVBgICAeHIgBSABQQBIG7JDAACAOZQhJSACIAhqLQAAIQUgAiAJai0AACEaIAIgCmotAAAhGyACIAtqLQAAIRwgAiAMai0AACEdIAIgDWotAAAhHiACIA5qLQAAIR8gAiAPai0AACEgIAIgEGotAAAhISACIBFqLQAAISIgBiIBBEADQAJ9ICVDAAAAAF0EQCAljBAAQwAAgL+SjAwBCyAlEABDAACAv5ILISUgAUEBRyEHIAFBAWshASAHDQALIAYhAQNAAn0gJEMAAAAAXQRAICSMEABDAACAv5KMDAELICQQAEMAAIC/kgshJCABQQFHIQcgAUEBayEBIAcNAAsgBiEBA0ACfSAjQwAAAABdBEAgI4wQAEMAAIC/kowMAQsgIxAAQwAAgL+SCyEjIAFBAUchByABQQFrIQEgBw0ACwsgACACQQN0ICUgJCAjICKzQwAAgD2UQwAAIMGSEAAgIbNDAACAPZRDAAAgwZIQACAgs0MAAIA9lEMAACDBkhAAQwAAAABDAACAPyAFs0MAAADDkkMAAAA8lCIjICOUIBuzQwAAAMOSQwAAADyUIiQgJJQgGrNDAAAAw5JDAAAAPJQiJSAllJKSkyImkSAmQwAAAABdGyAkICUgIyAeQQh0IB9yIB1BEHRyIBxBGHRyQQAQBiACQQFqIgIgA0cNAAsLC+kDAgR8BH0gACABQQJ0aiIAIAI4AgAgACANNgIMIAAgBDgCCCAAIAM4AgQgACAJIAsgC5QgCiAKlCAIIAiUIAkgCZSSkpKRIgSVIgIgCyAElSIDlCIJIAggBJUiCCAKIASVIgSUIgqSuyIOIA6gIAe7Ig6itiIHIAeURAAAAAAAAPA/IAQgBJQiCyADIAOUIhOSuyIQIBCgoSAFuyIQorYiBSAFlCACIASUIhIgCCADlCIUk7siESARoCAGuyIRorYiBiAGlJKSQwAAgECUEAkgByAEIAOUIhUgCCAClCIIk7siDyAPoCAOorYiA5QgBSASIBSSuyIPIA+gIBCitiIElCAGRAAAAAAAAPA/IAIgApQiEiATkrsiDyAPoKEgEaK2IgKUkpJDAACAQJQQCUEQdHI2AhAgACAHRAAAAAAAAPA/IBIgC5K7Ig8gD6ChIA6itiIHlCAFIAkgCpO7Ig4gDqAgEKK2IgWUIAYgFSAIkrsiDiAOoCARorYiBpSSkkMAAIBAlBAJIAMgA5QgBCAElCACIAKUkpJDAACAQJQQCUEQdHI2AhQgACAMNgIcIAAgAyAHlCAEIAWUIAIgBpSSkkMAAIBAlBAJIAcgB5QgBSAFlCAGIAaUkpJDAACAQJQQCUEQdHI2AhgLMgECf0GVowMhAQNAIAAgAmotAAAgAUEhbHMhASACQQFqIgJB/ABHDQALIAEgACgCfEcLvwEBAn8gAUEASgRAA0AgACADQQN0IAAgA0EFdGoiAioCACACKgIEIAIqAgggAioCDCACKgIQIAIqAhQgAi0AHLhEAAAAAAAAYMCgRAAAAAAAAIA/orYgAi0AHbhEAAAAAAAAYMCgRAAAAAAAAIA/orYgAi0AHrhEAAAAAAAAYMCgRAAAAAAAAIA/orYgAi0AH7hEAAAAAAAAYMCgRAAAAAAAAIA/orYgAigCGEEAEAYgA0EBaiIDIAFHDQALC0EAC3IBBH8gALwiBEH///8DcSEBAkAgBEEXdkH/AXEiAkUNACACQfAATQRAIAFBgICABHJB8QAgAmt2IQEMAQsgAkGNAUsEQEGA+AEhA0EAIQEMAQsgAkEKdEGAgAdrIQMLIAMgBEEQdkGAgAJxciABQQ12cgs=`;

export async function parseSpxHeader(header: Uint8Array): Promise<SpxHeader> {
    const ui32s = new Uint32Array(header.buffer);
    const f32s = new Float32Array(header.buffer);
    const head = new SpxHeader();
    head.Fixed = String.fromCharCode(header[0]) + String.fromCharCode(header[1]) + String.fromCharCode(header[2]);
    head.Version = header[3];
    head.SplatCount = ui32s[1];
    head.MinX = f32s[2];
    head.MaxX = f32s[3];
    head.MinY = f32s[4];
    head.MaxY = f32s[5];
    head.MinZ = f32s[6];
    head.MaxZ = f32s[7];
    head.MinTopY = f32s[8];
    head.MaxTopY = f32s[9];
    head.CreateDate = ui32s[10];
    head.CreaterId = ui32s[11];
    head.ExclusiveId = ui32s[12];
    head.ShDegree = header[52];
    head.Flags = header[53];
    head.Lod = header[54];
    head.Reserve3 = header[55];
    head.Reserve1 = ui32s[14];
    head.Reserve2 = ui32s[15];

    let comment: string = '';
    for (let i = 64; i < 124; i++) {
        comment += String.fromCharCode(header[i]);
    }
    head.Comment = comment.trim();

    head.HashCheck = true;
    if (head.Fixed !== 'spx') {
        return null;
    }

    // 哈希校验（检查模型是否由特定工具生成）
    const wasmBase64 = head.ExclusiveId ? WasmDataV3 : WasmOpen;
    const wasmModule = WebAssembly.compile(Uint8Array.from(atob(wasmBase64), c => c.charCodeAt(0)).buffer);
    const memory = new WebAssembly.Memory({ initial: 1, maximum: 1 });
    const instance = await WebAssembly.instantiate(await wasmModule, { env: { memory, expf } });
    const headerParser: any = instance.exports.H;

    const wasmMemory = new Uint8Array(memory.buffer);
    wasmMemory.set(header, 0);
    const code: number = headerParser(0);
    if (code) {
        head.HashCheck = false;
    }

    return head;
}

interface SpxBlockResult {
    splatCount: number;
    blockFormat: number;
    datas?: Uint8Array;
    isSplat?: boolean;
    isSh?: boolean;
    isSh1?: boolean;
    isSh2?: boolean;
    isSh3?: boolean;
    isSh23?: boolean;
    dataSh3?: Uint8Array;
    palettes?: Uint8Array;
    success: boolean;
}

export async function parseSpxBlockData(data: Uint8Array, header: SpxHeader = null): Promise<SpxBlockResult> {
    let ui32s = new Uint32Array(data.slice(0, 8).buffer);
    const splatCount = ui32s[0];
    const blockFormat = ui32s[1];
    const WebpBfs = [SpxBlockFormatData220, SpxBlockFormatData230, 300222, 300232];
    const isV3Webp = header?.Version >= 3 && WebpBfs.includes(blockFormat);

    if (blockFormat == SpxBlockFormatSH8) {
        const splatCount = 0;
        const palettes: Uint8Array = data.subarray(8);
        const success = true;
        return { splatCount, blockFormat, palettes, success };
    } else if (blockFormat == SpxBlockFormatSH9) {
        const { rgba } = await webpToRgba(data.subarray(8));
        const splatCount = 0;
        const palettes: Uint8Array = rgba;
        const success = true;
        return { splatCount, blockFormat, palettes, success };
    }

    let shDegree = header?.ShDegree || 0;
    if (blockFormat == SpxBlockFormatSH4) {
        if (header.ShDegree == SpxBlockFormatSH1) {
            const data1 = await sh123To1(data);
            return parseBlockData(splatCount, SpxBlockFormatSH1, data1, header.Version, shDegree);
        } else if (header.ShDegree == SpxBlockFormatSH2) {
            const data2 = await sh123To2(data);
            return parseBlockData(splatCount, SpxBlockFormatSH2, data2, header.Version, shDegree);
        } else if (header.ShDegree == SpxBlockFormatSH3) {
            const data2 = await sh123To2(data);
            const data3 = await sh123To3(data);
            const rs2 = await parseBlockData(splatCount, SpxBlockFormatSH2, data2, header.Version, shDegree);
            const rs3 = await parseBlockData(splatCount, SpxBlockFormatSH3, data3, header.Version, shDegree);
            rs2.success = rs2.success && rs3.success;
            rs2.isSh23 = true;
            rs2.dataSh3 = rs3.datas;
            return rs2;
        }
    }

    if (isV3Webp) {
        data = await decodeWebpBlockDatas(data);
    } else if (blockFormat == SpxBlockFormatData190) {
        data = await data190To19(data);
    } else if (blockFormat == SpxBlockFormatData10190) {
        data = await data10190To10019(data);
    }
    return parseBlockData(splatCount, blockFormat, data, header?.Version || 1, shDegree);
}

async function parseBlockData(splatCount: number, blockFormat: number, data: Uint8Array, spxVer: number, shDegree: number): Promise<SpxBlockResult> {
    const isSh1: boolean = SpxBlockFormatSH1 == blockFormat;
    const isSh2: boolean = SpxBlockFormatSH2 == blockFormat;
    const isSh3: boolean = SpxBlockFormatSH3 == blockFormat;
    const isSh: boolean = isSh1 || isSh2 || isSh3;
    const isSplat: boolean = !isSh;
    const wasms = [WasmOpen, WasmDataV1, WasmDataV2, WasmDataV3];
    const idx = blockFormat < 65536 ? 0 : spxVer;

    const resultByteLength = splatCount * (isSh ? SplatDataSize16 : SplatDataSize32);
    const wasmModule = WebAssembly.compile(Uint8Array.from(atob(wasms[idx]), c => c.charCodeAt(0)).buffer);
    const blockCnt: number = Math.ceil((resultByteLength + data.byteLength) / WasmBlockSize) + 1;
    const memory = new WebAssembly.Memory({ initial: blockCnt, maximum: blockCnt });
    const instance = await WebAssembly.instantiate(await wasmModule, { env: { memory, expf } });
    const dataParser: any = instance.exports.D;

    const wasmMemory = new Uint8Array(memory.buffer);
    wasmMemory.set(data, resultByteLength);
    const code = dataParser(0, resultByteLength, shDegree);
    if (code) return { splatCount, blockFormat, success: false };
    return { splatCount, blockFormat, success: true, datas: wasmMemory.slice(0, resultByteLength), isSplat, isSh, isSh1, isSh2, isSh3 };
}

export async function parseSplatToTexdata(data: Uint8Array, splatCount: number): Promise<Uint8Array> {
    const wasmModule = WebAssembly.compile(Uint8Array.from(atob(WasmOpen), c => c.charCodeAt(0)).buffer);
    const blockCnt = Math.ceil((splatCount * SplatDataSize32) / WasmBlockSize) + 1;
    const memory = new WebAssembly.Memory({ initial: blockCnt, maximum: blockCnt });
    const instance = await WebAssembly.instantiate(await wasmModule, { env: { memory, expf } });
    const dataParser: any = instance.exports.s;

    const wasmMemory = new Uint8Array(memory.buffer);
    wasmMemory.set(data.subarray(0, splatCount * SplatDataSize32), 0);
    const code: number = dataParser(0, splatCount);
    if (code) {
        console.error('splat data parser failed:', code);
        return new Uint8Array(0);
    }

    return wasmMemory.slice(0, splatCount * SplatDataSize32);
}

export async function parseWordToTexdata(x: number, y0z: number, isY: boolean = true, isNgativeY: boolean = true): Promise<Uint8Array> {
    const wasmModule = WebAssembly.compile(Uint8Array.from(atob(WasmDataV2), c => c.charCodeAt(0)).buffer);
    const memory = new WebAssembly.Memory({ initial: 1, maximum: 1 });
    const instance = await WebAssembly.instantiate(await wasmModule, { env: { memory, expf } });
    const dataSplat: any = instance.exports.w;

    const wasmMemory = new Uint8Array(memory.buffer);
    const f32s = new Float32Array(wasmMemory.buffer);
    const ngativeY = isNgativeY ? -1 : 1;
    f32s[0] = x;
    isY ? (f32s[1] = ngativeY * y0z) : (f32s[2] = ngativeY * y0z);
    dataSplat(0, isY ? 1 : 0);
    return wasmMemory.slice(0, SplatDataSize32);
}

function expf(v: number) {
    return Math.exp(v);
}
