// ==============================================
// Copyright (c) 2025 reall3d.com, MIT license
// ==============================================
import { data190To19, data10190To10019, sh123To1, sh123To2, sh123To3, webpToRgba, data220Decode, decodeWebpBlockDatas } from '../../utils/CommonUtils';
import {
    SplatDataSize16,
    SplatDataSize32,
    SpxBlockFormatData190,
    SpxBlockFormatData10190,
    SpxBlockFormatSH1,
    SpxBlockFormatSH2,
    SpxBlockFormatSH3,
    SpxBlockFormatSH4,
    WasmBlockSize,
    SpxBlockFormatSH8,
    SpxBlockFormatSH9,
    SpxBlockFormatData220,
} from '../../utils/consts/GlobalConstants';
import { SpxHeader } from '../ModelData';

const WasmDataV1 = `AGFzbQEAAAAADwhkeWxpbmsuMAEEAAAAAAEeBmABfQF9YAAAYAJ/fwF/YAF9AX9gAX8Bf2ACf38AAhoCA2VudgRleHBmAAADZW52Bm1lbW9yeQIAAAMGBQECAwQFByEEEV9fd2FzbV9jYWxsX2N0b3JzAAEBSAAEAXcABQFEAAIKhAsFAwABC6MJAyh/Dn0EfCABKAIEQYvwCUcEQEEBDwsgASgCACIEQQBMBEBBAA8LIAFBCWoiAiAEQRNsaiEHIAIgBEESbGohCCACIARBEWxqIQkgAiAEQQR0aiEKIAIgBEEPbGohCyACIARBDmxqIQwgAiAEQQ1saiENIAIgBEEMbGohDiACIARBC2xqIQ8gAiAEQQpsaiEQIAIgBEEJbGohESACIARBBmxqIRIgAiAEQQNsaiETQQAhAiABLQAIIRQDQCACIAhqLQAAIRUgAiAJai0AACEWIAIgCmotAAAhFyACIAtqLQAAIRggAiAMai0AACEZIAIgDWotAAAhGiACIA5qLQAAIRsgAiAPai0AACEcIAIgEGotAAAhHSACIBFqLQAAIR4gEiACQQNsIgNqIgUtAAAhHyADIBNqIgYtAAAhICABIANqIgMtAAohISADLQAJISIgBS0AASEjIAYtAAEhJCADLQALIiXAISYgBS0AAiInwCEoIAYtAAIiBsAhKUEAIQUgFARAIAcgAkEBdGoiAy0AASIFQQh0QYD+AXEgAy0AAHIgBUEJdEGAgARxciEFCyAAIAJBBXRqIgMgBTYCDCADICNBCHQgH3IgJ0EQdHIiBUGAgIB4ciAFIChBAEgbskMAAIA5lDgCCCADICRBCHQgIHIgBkEQdHIiBUGAgIB4ciAFIClBAEgbskMAAIA5lDgCBCADICFBCHQgInIgJUEQdHIiBUGAgIB4ciAFICZBAEgbskMAAIA5lDgCACAcs0MAAIA9lEMAACDBkhAAIS8gHbNDAACAPZRDAAAgwZIQACExIAMgF7NDAAAAw5JDAAAAPJQiKyAVs0MAAADDkkMAAAA8lCItIC2UIiogFrNDAAAAw5JDAAAAPJQiLiAulCIsQwAAAABDAACAPyAqICwgKyArlCIrkpKTIiqRICpDAAAAAF0bIiwgLJQgK5KSkpEiKpUiKyAtICqVIi2UIjMgLCAqlSIwIC4gKpUiKpQiNJK7IjggOKAgL7siOKK2Ii4gLpREAAAAAAAA8D8gKiAqlCI1IC0gLZQiNpK7IjogOqChIB6zQwAAgD2UQwAAIMGSEAC7IjqitiIsICyUICsgKpQiMiAwIC2UIjeTuyI7IDugIDG7IjuitiIvIC+UkpJDAACAQJQQAyAuICogLZQiMSAwICuUIjCTuyI5IDmgIDiitiItlCAsIDIgN5K7IjkgOaAgOqK2IiqUIC9EAAAAAAAA8D8gKyArlCIyIDaSuyI5IDmgoSA7orYiK5SSkkMAAIBAlBADQRB0cjYCECADIC5EAAAAAAAA8D8gMiA1krsiOSA5oKEgOKK2Ii6UICwgMyA0k7siOCA4oCA6orYiLJQgLyAxIDCSuyI4IDigIDuitiIvlJKSQwAAgECUEAMgLSAtlCAqICqUICsgK5SSkkMAAIBAlBADQRB0cjYCFCADIBpBCHQgG3IgGUEQdHIgGEEYdHI2AhwgAyAtIC6UICogLJQgKyAvlJKSQwAAgECUEAMgLiAulCAsICyUIC8gL5SSkkMAAIBAlBADQRB0cjYCGCACQQFqIgIgBEcNAAtBAAtyAQR/IAC8IgRB////A3EhAQJAIARBF3ZB/wFxIgJFDQAgAkHwAE0EQCABQYCAgARyQfEAIAJrdiEBDAELIAJBjQFLBEBBgPgBIQNBACEBDAELIAJBCnRBgIAHayEDCyADIARBEHZBgIACcXIgAUENdnILMgECf0HBphYhAQNAIAAgAmotAAAgAUEhbHMhASACQQFqIgJB/ABHDQALIAEgACgCfEcLMwAgAEEIQQQgAUEBRhtqQQA2AgAgAEEANgAcIAD9DAAAAQCMERYAlQFsEu2BMhP9CwIMCw==`;
const WasmDataV2 = `AGFzbQEAAAAADwhkeWxpbmsuMAEEAAAAAAEeBmABfQF9YAAAYAJ/fwF/YAF9AX9gAX8Bf2ACf38AAhoCA2VudgRleHBmAAADZW52Bm1lbW9yeQIAAAMGBQECAwQFByEEEV9fd2FzbV9jYWxsX2N0b3JzAAEBSAAEAXcABQFEAAIK3gwFAwABC+wKAy1/Dn0EfCABKAIEQfiuDUcEQEEBDwsgASgCACICQQBKBEAgAUEJaiIDIAJBE2xqIQcgAyACQRJsaiEIIAMgAkERbGohCSADIAJBD2xqIQogAyACQQ5saiELIAMgAkENbGohDCADIAJBDGxqIQ0gAyACQQtsaiEOIAMgAkEKbGohDyADIAJBCWxqIRAgAyACQQN0aiERIAMgAkEHbGohEiADIAJBBmxqIRMgAyACQQVsaiEUIAMgAkECdGohFSADIAJBA2xqIRYgAyACQQF0aiEXIAEgAmpBCWohGCABIAJBBHRqQQlqIRkgAS0ACCEaQQAhAQNAIAEgFGotAAAhBCABIBVqLQAAIRsgASAWai0AACEcIAEgF2otAAAhHSABIBhqLQAAIR4gASADai0AACEfIAEgEWotAAAiIMAhISABIBJqLQAAIiLAISMgASATai0AACIkwCElQQAhBSAaBEAgByABQQF0aiIFLQABIgZBCHRBgP4BcSAFLQAAciAGQQl0QYCABHFyIQULIAEgCGotAAAhBiABIAlqLQAAISYgASAZai0AACEnIAEgCmotAAAhKCABIAtqLQAAISkgASAMai0AACEqIAEgDWotAAAhKyABIA5qLQAAISwgASAPai0AACEtIAEgEGotAAAhLiAEQQh0IB1yICBBEHRyIgRBgICAeHIgBCAhQQBIG7IhMiAbQQh0IB5yICJBEHRyIgRBgICAeHIgBCAjQQBIG7JDAACAOZQhMAJ9IBxBCHQgH3IgJEEQdHIiBEGAgIB4ciAEICVBAEgbskMAAIA5lCIvQwAAAABdBEAgL4wQAEMAAIC/kowMAQsgLxAAQwAAgL+SCyExIDJDAACAOZQhLwJ9IDBDAAAAAF0EQCAwjBAAQwAAgL+SjAwBCyAwEABDAACAv5ILITACfSAvQwAAAABdBEAgL4wQAEMAAIC/kowMAQsgLxAAQwAAgL+SCyEvIAAgAUEFdGoiBCAxOAIAIAQgBTYCDCAEIC84AgggBCAwOAIEICyzQwAAgD2UQwAAIMGSEAAhNCAts0MAAIA9lEMAACDBkhAAITYgBCAns0MAAADDkkMAAAA8lCIwIAazQwAAAMOSQwAAADyUIi8gL5QiMSAms0MAAADDkkMAAAA8lCIyIDKUIjNDAAAAAEMAAIA/IDEgMyAwIDCUIjCSkpMiMZEgMUMAAAAAXRsiMyAzlCAwkpKSkSIxlSIwIC8gMZUiL5QiOCAzIDGVIjUgMiAxlSIxlCI5krsiPSA9oCA0uyI9orYiMiAylEQAAAAAAADwPyAxIDGUIjogLyAvlCI7krsiPyA/oKEgLrNDAACAPZRDAAAgwZIQALsiP6K2IjMgM5QgMCAxlCI3IDUgL5QiPJO7IkAgQKAgNrsiQKK2IjQgNJSSkkMAAIBAlBADIDIgMSAvlCI2IDUgMJQiNZO7Ij4gPqAgPaK2Ii+UIDMgNyA8krsiPiA+oCA/orYiMZQgNEQAAAAAAADwPyAwIDCUIjcgO5K7Ij4gPqChIECitiIwlJKSQwAAgECUEANBEHRyNgIQIAQgMkQAAAAAAADwPyA3IDqSuyI+ID6goSA9orYiMpQgMyA4IDmTuyI9ID2gID+itiIzlCA0IDYgNZK7Ij0gPaAgQKK2IjSUkpJDAACAQJQQAyAvIC+UIDEgMZQgMCAwlJKSQwAAgECUEANBEHRyNgIUIAQgKkEIdCArciApQRB0ciAoQRh0cjYCHCAEIC8gMpQgMSAzlCAwIDSUkpJDAACAQJQQAyAyIDKUIDMgM5QgNCA0lJKSQwAAgECUEANBEHRyNgIYIAFBAWoiASACRw0ACwtBAAtyAQR/IAC8IgRB////A3EhAQJAIARBF3ZB/wFxIgJFDQAgAkHwAE0EQCABQYCAgARyQfEAIAJrdiEBDAELIAJBjQFLBEBBgPgBIQNBACEBDAELIAJBCnRBgIAHayEDCyADIARBEHZBgIACcXIgAUENdnILQwECf0GVowNBwaYWIAAoAjBBx92XvQRGGyEBA0AgACACai0AACABQSFscyEBIAJBAWoiAkH8AEcNAAsgASAAKAJ8RwszACAAQQhBBCABQQFGG2pBADYCACAAQQA2ABwgAP0MAAABAIwRFgCVAWwS7YEyE/0LAgwL`;
const WasmDataV3 = `AGFzbQEAAAAADwhkeWxpbmsuMAEEAAAAAAEwB2ABfQF9YAAAYAN/f38Bf2AOf399fX19fX19fX19f38AYAF/AX9gAn9/AGABfQF/AhoCA2VudgRleHBmAAADZW52Bm1lbW9yeQIAAAMHBgECAwQFBgchBBFfX3dhc21fY2FsbF9jdG9ycwABAUgABAF3AAUBRAACCroUBgMAAQvdDgIwfw19AkAgASgCBCIEQfanEkcEQCAEQb6pEkcEQEEBDwsgASgCACIEQQBMDQEgBEEYbEEIaiEQIARBFGxBCGohESAEQQR0QQhyIRIgBEEMbEEIaiETIARBA3RBCGohFCAEQQJ0QQhqIRVBHEEYIAEtAAsiFkH+AUYbIARsQQhqIRcDQCABIApBAnQiA2ohBiABIAMgE2pqIQUgASADIBRqaiIILQAAIQ4gASADIBVqaiEJIAgtAAIhDyAILQABIQggFkH+AUYEQCAFLQADQf8BcyABIAMgEGpqIgstAABBAXRyIAstAAFBCXRyIQsLIAYtAAohDCAGLQAJIRggBi0ACCEZIAktAAAhGiAJLQACIRsgCS0AASEJIAJBAEoEQCABIAMgF2pqIgctAAFBCHQgBy0AAHIhBwsgASADIBFqaiIGLQAAIRwgASADIBJqaiIDLQAAIR0gBS0AACEeIAYtAAMhHyAGLQACISAgBi0AASEGIAMtAAMhISADLQACISIgAy0AASEDIAUtAAIhDSAFLQABIQUgG0EIdCAMciAPQRB0ciIMQYCAgHhyIAwgD8BBAEgbsiE1IAlBCHQgGHIgCEEQdHIiCUGAgIB4ciAJIAjAQQBIG7JDAACAOZQhNAJ9IBpBCHQgGXIgDkEQdHIiCEGAgIB4ciAIIA7AQQBIG7JDAACAOZQiM0MAAAAAXQRAIDOMEABDAACAv5KMDAELIDMQAEMAAIC/kgshOiA1QwAAgDmUITMCfSA0QwAAAABdBEAgNIwQAEMAAIC/kowMAQsgNBAAQwAAgL+SCyE7An0gM0MAAAAAXQRAIDOMEABDAACAv5KMDAELIDMQAEMAAIC/kgshPCADQQh0IB1yICJBEHRyICFBGHRyIQMgDbNDAACAPZRDAAAgwZIQACE9IAWzQwAAgD2UQwAAIMGSEAAhPiAes0MAAIA9lEMAACDBkhAAIT9DAAAAAEMAAIA/ICCzQwAAf0OVQwAAAL+SQ/MEtT+UIjMgM5QgHLNDAAB/Q5VDAAAAv5JD8wS1P5QiNCA0lCAGs0MAAH9DlUMAAAC/kkPzBLU/lCI3IDeUkpKTIjWRIDVDAAAAAF0bIjkhOCAzITUgNyE2AkACfQJAAkACQCAfQfwBaw4DBAABAgsgNCE4IDkhNAwDCyA0ITggOSE2IDMMAQsgNCE4IDMhNiA5CyE1IDchNAsgACAKQQN0IDogOyA8ID8gPiA9IDggNCA2IDUgAyAHIAtBEHRyEAMgCkEBaiIKIARHDQALDAELIAEoAgAiBEEATA0AIAFBCWoiAyAEQRVsaiEIIAMgBEEUbGohDiADIARBE2xqIQkgAyAEQRJsaiEPIAMgBEERbGohECADIARBD2xqIREgAyAEQQ5saiESIAMgBEENbGohEyADIARBDGxqIRQgAyAEQQtsaiEVIAMgBEEKbGohFiADIARBCWxqIRcgAyAEQQN0aiEMIAMgBEEHbGohGCADIARBBmxqIRkgAyAEQQVsaiEaIAMgBEECdGohGyADIARBA2xqIRwgAyAEQQF0aiEdIAEgBGpBCWohHiABIARBBHRqQQlqIR8gA0EWQRQgAS0ACCIgGyAEbGoiISAEaiEiQQAhAQNAIAEgDGotAAAhBSABIBhqLQAAIQYgASAZai0AACELICAEQCABIA5qLQAAIAEgCGotAABBCHRyIQcLIAEgGmotAAAhDSABIBtqLQAAISMgASAcai0AACEkIAEgHWotAAAhJSABIB5qLQAAISYgASADai0AACEnIAJBAEoEQCABICFqLQAAIAEgImotAABBCHRyIQoLIAEgCWotAAAhKCABIA9qLQAAISkgASAQai0AACEqIAEgH2otAAAhKyABIBFqLQAAISwgASASai0AACEtIAEgE2otAAAhLiABIBRqLQAAIS8gASAVai0AACEwIAEgFmotAAAhMSABIBdqLQAAITIgDUEIdCAlciAFQRB0ciINQYCAgHhyIA0gBcBBAEgbsiE2ICNBCHQgJnIgBkEQdHIiBUGAgIB4ciAFIAbAQQBIG7JDAACAOZQhNAJ9ICRBCHQgJ3IgC0EQdHIiBUGAgIB4ciAFIAvAQQBIG7JDAACAOZQiM0MAAAAAXQRAIDOMEABDAACAv5KMDAELIDMQAEMAAIC/kgshNSA2QwAAgDmUITMgACABQQN0IDUCfSA0QwAAAABdBEAgNIwQAEMAAIC/kowMAQsgNBAAQwAAgL+SCwJ9IDNDAAAAAF0EQCAzjBAAQwAAgL+SjAwBCyAzEABDAACAv5ILIDKzQwAAgD2UQwAAIMGSEAAgMbNDAACAPZRDAAAgwZIQACAws0MAAIA9lEMAACDBkhAAICuzQwAAAMOSQwAAADyUICqzQwAAAMOSQwAAADyUICmzQwAAAMOSQwAAADyUICizQwAAAMOSQwAAADyUIC5BCHQgL3IgLUEQdHIgLEEYdHIgCiAHQRB0chADIAFBAWoiASAERw0ACwtBAAvpAwIEfAR9IAAgAUECdGoiACACOAIAIAAgDTYCDCAAIAQ4AgggACADOAIEIAAgCSALIAuUIAogCpQgCCAIlCAJIAmUkpKSkSIElSICIAsgBJUiA5QiCSAIIASVIgggCiAElSIElCIKkrsiDiAOoCAHuyIOorYiByAHlEQAAAAAAADwPyAEIASUIgsgAyADlCITkrsiECAQoKEgBbsiEKK2IgUgBZQgAiAElCISIAggA5QiFJO7IhEgEaAgBrsiEaK2IgYgBpSSkkMAAIBAlBAGIAcgBCADlCIVIAggApQiCJO7Ig8gD6AgDqK2IgOUIAUgEiAUkrsiDyAPoCAQorYiBJQgBkQAAAAAAADwPyACIAKUIhIgE5K7Ig8gD6ChIBGitiIClJKSQwAAgECUEAZBEHRyNgIQIAAgB0QAAAAAAADwPyASIAuSuyIPIA+goSAOorYiB5QgBSAJIAqTuyIOIA6gIBCitiIFlCAGIBUgCJK7Ig4gDqAgEaK2IgaUkpJDAACAQJQQBiADIAOUIAQgBJQgAiAClJKSQwAAgECUEAZBEHRyNgIUIAAgDDYCHCAAIAMgB5QgBCAFlCACIAaUkpJDAACAQJQQBiAHIAeUIAUgBZQgBiAGlJKSQwAAgECUEAZBEHRyNgIYC0MBAn9BlaMDQcGmFiAAKAIwQcfdl70ERhshAQNAIAAgAmotAAAgAUEhbHMhASACQQFqIgJB/ABHDQALIAEgACgCfEcLMwAgAEEIQQQgAUEBRhtqQQA2AgAgAEEANgAcIAD9DAAAAQCMERYAlQFsEu2BMhP9CwIMC3IBBH8gALwiBEH///8DcSEBAkAgBEEXdkH/AXEiAkUNACACQfAATQRAIAFBgICABHJB8QAgAmt2IQEMAQsgAkGNAUsEQEGA+AEhA0EAIQEMAQsgAkEKdEGAgAdrIQMLIAMgBEEQdkGAgAJxciABQQ12cgs=`;
const WasmOpen = `AGFzbQEAAAAADwhkeWxpbmsuMAEEAAAAAAExB2ABfQF9YAAAYAN/f38Bf2AOf399fX19fX19fX19f38AYAF/AX9gAn9/AX9gAX0BfwIaAgNlbnYEZXhwZgAAA2VudgZtZW1vcnkCAAADBwYBAgMEBQYHIQQRX193YXNtX2NhbGxfY3RvcnMAAQFIAAQBcwAFAUQAAgq5KgYDAAEL4CMCL38MfUEBIQUCQAJAAn8CQAJAAkACQCABKAIEIgNBEkwEQCADQQFrDgMBAgMHCwJAAkACQCADQRNrDgQGAgkBAAtBDCADQaPOAEYNBhogA0HcAUcNCCABKAIAIgVBAEwNByAFQRhsQQhqIQwgBUEUbEEIaiENIAVBBHRBCHIhDiAFQQxsQQhqIQ8gBUEDdEEIaiEQIAVBAnRBCGohEUEAIQMDQCABIANBAnQiBGoiBi0ACiEIIAYtAAkhCiAGLQAIIRIgASAEIBFqaiIGLQAAIRMgASAEIBBqaiIHLQAAIhTAIRUgBi0AAiEWIAYtAAEhFyAHLQACIhjAIRkgBy0AASIJwCEaIAJBAEoEQCABIAQgDGpqIgYtAAFBCHQgBi0AAHIhHwsgASAEIA1qaiIGLQAAIRsgASAEIA5qaiIHLQAAIRwgASAEIA9qaiIELQAAIQsgBi0AAyEdIAYtAAIhICAGLQABIQYgBy0AAyEhIActAAIhIiAHLQABIQcgBC0AAiEeIAQtAAEhBCAWQQh0IAhyIBhBEHRyIghBgICAeHIgCCAZQQBIGyEIIBdBCHQgCnIgCUEQdHIiCkGAgIB4ciAKIBpBAEgbsiEzAn0gE0EIdCASciAUQRB0ciIKQYCAgHhyIAogFUEASBuyQwAAgDmUIjJDAAAAAF0EQCAyjBAAQwAAgL+SjAwBCyAyEABDAACAv5ILITggCLIhNAJ9IDNDAACAOZQiMkMAAAAAXQRAIDKMEABDAACAv5KMDAELIDIQAEMAAIC/kgshOQJ9IDRDAACAOZQiMkMAAAAAXQRAIDKMEABDAACAv5KMDAELIDIQAEMAAIC/kgshOiAHQQh0IBxyICJBEHRyICFBGHRyIQcgHrNDAACAPZRDAAAgwZIQACE7IASzQwAAgD2UQwAAIMGSEAAhPCALs0MAAIA9lEMAACDBkhAAIT1DAAAAAEMAAIA/ICCzQwAAf0OVQwAAAL+SQ/MEtT+UIjUgNZQgG7NDAAB/Q5VDAAAAv5JD8wS1P5QiMiAylCAGs0MAAH9DlUMAAAC/kkPzBLU/lCI2IDaUkpKTIjORIDNDAAAAAF0bIjchMyA2ITQCQAJ9AkACQAJAIB1B/AFrDgMEAAECCyAyITMgNyEyDAMLIDIhMyA3ITQgNQwBCyAyITMgNSE0IDcLITUgNiEyCyAAIANBA3QgOCA5IDogPSA8IDsgMyAyIDQgNSAHIB8QAyADQQFqIgMgBUcNAAsMBwsgASgCACIFQQBMDQYgAUEIaiIEIAVBFWxqIQYgBCAFQRRsaiEHIAQgBUETbGohDCAEIAVBEmxqIQ0gBCAFQRFsaiEOIAQgBUEPbGohDyAEIAVBDmxqIRAgBCAFQQ1saiERIAQgBUEMbGohCCAEIAVBC2xqIQogBCAFQQpsaiESIAQgBUEJbGohEyAEIAVBA3RqIRQgBCAFQQdsaiEVIAQgBUEGbGohFiAEIAVBBWxqIRcgBCAFQQJ0aiEYIAQgBUEDbGohGSAEIAVBAXRqIQkgASAFakEIaiEaIAEgBUEEdGpBCGohH0EAIQNBACEBA0AgAyAXai0AACEbIAMgGGotAAAhHCADIBlqLQAAIQsgAyAJai0AACEdIAMgGmotAAAhICADIARqLQAAISEgAyAUai0AACIiwCEeIAMgFWotAAAiI8AhJCADIBZqLQAAIiXAISYgAkEASgRAIAMgB2otAAAgAyAGai0AAEEIdHIhAQsgAyAMai0AACEnIAMgDWotAAAhKCADIA5qLQAAISkgAyAfai0AACEqIAMgD2otAAAhKyADIBBqLQAAISwgAyARai0AACEtIAMgCGotAAAhLiADIApqLQAAIS8gAyASai0AACEwIAMgE2otAAAhMSAcQQh0ICByICNBEHRyIhxBgICAeHIgHCAkQQBIG7IhMyAbQQh0IB1yICJBEHRyIhtBgICAeHIgGyAeQQBIG7IhNCAAIANBA3QCfSALQQh0ICFyICVBEHRyIhtBgICAeHIgGyAmQQBIG7JDAACAOZQiMkMAAAAAXQRAIDKMEABDAACAv5KMDAELIDIQAEMAAIC/kgsCfSAzQwAAgDmUIjJDAAAAAF0EQCAyjBAAQwAAgL+SjAwBCyAyEABDAACAv5ILAn0gNEMAAIA5lCIyQwAAAABdBEAgMowQAEMAAIC/kowMAQsgMhAAQwAAgL+SCyAxs0MAAIA9lEMAACDBkhAAIDCzQwAAgD2UQwAAIMGSEAAgL7NDAACAPZRDAAAgwZIQACAqs0MAAADDkkMAAAA8lCAps0MAAADDkkMAAAA8lCAos0MAAADDkkMAAAA8lCAns0MAAADDkkMAAAA8lCAtQQh0IC5yICxBEHRyICtBGHRyIAEQAyADQQFqIgMgBUcNAAsMBgsgASgCACICQQBMDQUgAUEIaiIDIAJBE2xqIQYgAyACQRJsaiEHIAMgAkERbGohDCADIAJBBHRqIQ0gAyACQQ9saiEOIAMgAkEObGohDyADIAJBDWxqIRAgAyACQQxsaiERIAMgAkELbGohCCADIAJBCmxqIQogAyACQQlsaiESIAMgAkEGbGohEyADIAJBA2xqIRRBACEFQQAhAwNAIAMgEGotAAAhFSADIBFqLQAAIRYgAyAPai0AACEXIAMgDmotAAAhGCADIAZqLQAAIRkgAyAHai0AACEJIAMgDGotAAAhGiADIA1qLQAAIR8gAyAIai0AACEbIAMgCmotAAAhHCAAIANBA3QgASADQQNsIgRqIgsvAAggCywACiILQf8BcUEQdHIiHUGAgIB4ciAdIAtBAEgbskMAAIA5lCAEIBRqIgsvAAAgCywAAiILQf8BcUEQdHIiHUGAgIB4ciAdIAtBAEgbskMAAIA5lCAEIBNqIgQvAAAgBCwAAiIEQf8BcUEQdHIiC0GAgIB4ciALIARBAEgbskMAAIA5lCADIBJqLQAAs0MAAIA9lEMAACDBkhAAIByzQwAAgD2UQwAAIMGSEAAgG7NDAACAPZRDAAAgwZIQACAfuEQAAAAAAABgwKBEAAAAAAAAgD+itiAauEQAAAAAAABgwKBEAAAAAAAAgD+itiAJuEQAAAAAAABgwKBEAAAAAAAAgD+itiAZuEQAAAAAAABgwKBEAAAAAAAAgD+itiAWIBVBCHRyIBdBEHRyIBhBGHRyQQAQAyADQQFqIgMgAkcNAAsMBgtBACEFIAEoAgAiBkEATA0FQQAhAwNAIAEgA0EJbGoiAi0ADSEHIAItAAwhDCACLQALIQ0gAi0ACiEOIAItAAkhDyACLQAIIRAgAi0AECERIAItAA8hCCACLQAOIQIgACADQQR0aiIEQoCAgIAQNwIIIAQgEUEQdEGAgOAHcSAIQRV0QYCAgPgBcSACQRp0QYCAgIB+cXJyNgIEIAQgB0EBdkH8AHEgDEEEdEGAH3EgDUEJdEGA4AdxIA5BDnRBgID4AXEgD0ETdEGAgIA+cSAQQRh0QYCAgEBxcnJycnIgAkEGdnI2AgAgA0EBaiIDIAZHDQALDAULQQAhBSABKAIAIgxBAEwNBEEAIQMDQCABIANBGGxqIgItABohDSACLQAZIQ4gAi0AGCEPIAItABchECACLQAWIREgAi0AFSEIIAItAA0hCiACLQAMIRIgAi0ACyETIAItAAohFCACLQAJIRUgAi0ACCEWIAItABQhBiACLQATIRcgAi0AEiEYIAItABEhGSACLQAQIQkgAi0ADyEaIAItAA4hByAAIANBBHRqIgQgAi0AH0EFdEGAPnEgAi0AHkEKdEGAwA9xIAItAB1BD3RBgIDwA3EgAi0AHEEUdEGAgID8AHEgAi0AGyICQRl0QYCAgIB/cXJycnJBAXI2AgwgBCAXQQF0QfADcSAYQQZ0QYD8AHEgGUELdEGAgB9xIAlBEHRBgIDgB3EgGkEVdEGAgID4AXEgB0EadEGAgICAfnFycnJyciAGQQR2cjYCBCAEIApBAXZB/ABxIBJBBHRBgB9xIBNBCXRBgOAHcSAUQQ50QYCA+AFxIBVBE3RBgICAPnEgFkEYdEGAgIBAcXJycnJyIAdBBnZyNgIAIAQgDUECdkE+cSAOQQN0QcAPcSAPQQh0QYDwA3EgEEENdEGAgPwAcSARQRJ0QYCAgB9xIAhBF3RBgICA4AdxIAZBHHRBgICAgHhxcnJycnJyIAJBB3ZyNgIIIANBAWoiAyAMRw0ACwwEC0EAIQUgASgCACIMQQBMDQNBACEDA0AgASADQRVsaiICLQAaIQ0gAi0AGSEOIAItABghDyACLQAXIRAgAi0AFiERIAItABUhCCACLQANIQogAi0ADCESIAItAAshEyACLQAKIRQgAi0ACSEVIAItAAghFiACLQAUIQYgAi0AEyEXIAItABIhGCACLQARIRkgAi0AECEJIAItAA8hGiACLQAOIQcgACADQQR0aiIEIAItABxBFHRBgICA/ABxIAItABsiAkEZdEGAgICAf3FyQQFyNgIMIAQgF0EBdEHwA3EgGEEGdEGA/ABxIBlBC3RBgIAfcSAJQRB0QYCA4AdxIBpBFXRBgICA+AFxIAdBGnRBgICAgH5xcnJycnIgBkEEdnI2AgQgBCAKQQF2QfwAcSASQQR0QYAfcSATQQl0QYDgB3EgFEEOdEGAgPgBcSAVQRN0QYCAgD5xIBZBGHRBgICAQHFycnJyciAHQQZ2cjYCACAEIA1BAnZBPnEgDkEDdEHAD3EgD0EIdEGA8ANxIBBBDXRBgID8AHEgEUESdEGAgIAfcSAIQRd0QYCAgOAHcSAGQRx0QYCAgIB4cXJycnJyciACQQd2cjYCCCADQQFqIgMgDEcNAAsMAwtBCAshAyAAIQVBACECIAEoAgAhBCADQQxGBEAgAS0ACCECCyAEQQBKBEAgASADaiIDIARBEmxqIQYgAyAEQRFsaiEHIAMgBEEEdGohDCADIARBD2xqIQ0gAyAEQQ5saiEOIAMgBEENbGohDyADIARBDGxqIRAgAyAEQQtsaiERIAMgBEEKbGohCCADIARBCWxqIQogAyAEQQN0aiESIAMgBEEHbGohEyADIARBBmxqIRQgAyAEQQVsaiEVIAMgBEECdGohFiADIARBA2xqIRcgAyAEQQF0aiEYIAMgBGohGUEAIQEDQCABIBhqLQAAIAEgFWotAABBCHRyIAEgEmosAAAiAEH/AXFBEHRyIglBgICAeHIgCSAAQQBIG7JDAACAOZQhMiABIBlqLQAAIAEgFmotAABBCHRyIAEgE2osAAAiAEH/AXFBEHRyIglBgICAeHIgCSAAQQBIG7JDAACAOZQhMyABIANqLQAAIAEgF2otAABBCHRyIAEgFGosAAAiAEH/AXFBEHRyIglBgICAeHIgCSAAQQBIG7JDAACAOZQhNCABIAZqLQAAIQkgASAHai0AACEaIAEgDGotAAAhHyABIA1qLQAAIRsgASAOai0AACEcIAEgD2otAAAhCyABIBBqLQAAIR0gASARai0AACEgIAEgCGotAAAhISABIApqLQAAISIgAiIABEADQAJ9IDRDAAAAAF0EQCA0jBAAQwAAgL+SjAwBCyA0EABDAACAv5ILITQgAEEBRyEeIABBAWshACAeDQALIAIhAANAAn0gM0MAAAAAXQRAIDOMEABDAACAv5KMDAELIDMQAEMAAIC/kgshMyAAQQFHIR4gAEEBayEAIB4NAAsgAiEAA0ACfSAyQwAAAABdBEAgMowQAEMAAIC/kowMAQsgMhAAQwAAgL+SCyEyIABBAUchHiAAQQFrIQAgHg0ACwsgBSABQQN0IDQgMyAyICKzQwAAgD2UQwAAIMGSEAAgIbNDAACAPZRDAAAgwZIQACAgs0MAAIA9lEMAACDBkhAAQwAAAABDAACAPyAJs0MAAADDkkMAAAA8lCIyIDKUIB+zQwAAAMOSQwAAADyUIjMgM5QgGrNDAAAAw5JDAAAAPJQiNCA0lJKSkyI1kSA1QwAAAABdGyAzIDQgMiALQQh0IB1yIBxBEHRyIBtBGHRyQQAQAyABQQFqIgEgBEcNAAsLC0EAIQULIAUL6QMCBHwEfSAAIAFBAnRqIgAgAjgCACAAIA02AgwgACAEOAIIIAAgAzgCBCAAIAkgCyALlCAKIAqUIAggCJQgCSAJlJKSkpEiBJUiAiALIASVIgOUIgkgCCAElSIIIAogBJUiBJQiCpK7Ig4gDqAgB7siDqK2IgcgB5REAAAAAAAA8D8gBCAElCILIAMgA5QiE5K7IhAgEKChIAW7IhCitiIFIAWUIAIgBJQiEiAIIAOUIhSTuyIRIBGgIAa7IhGitiIGIAaUkpJDAACAQJQQBiAHIAQgA5QiFSAIIAKUIgiTuyIPIA+gIA6itiIDlCAFIBIgFJK7Ig8gD6AgEKK2IgSUIAZEAAAAAAAA8D8gAiAClCISIBOSuyIPIA+goSARorYiApSSkkMAAIBAlBAGQRB0cjYCECAAIAdEAAAAAAAA8D8gEiALkrsiDyAPoKEgDqK2IgeUIAUgCSAKk7siDiAOoCAQorYiBZQgBiAVIAiSuyIOIA6gIBGitiIGlJKSQwAAgECUEAYgAyADlCAEIASUIAIgApSSkkMAAIBAlBAGQRB0cjYCFCAAIAw2AhwgACADIAeUIAQgBZQgAiAGlJKSQwAAgECUEAYgByAHlCAFIAWUIAYgBpSSkkMAAIBAlBAGQRB0cjYCGAsyAQJ/QZWjAyEBA0AgACACai0AACABQSFscyEBIAJBAWoiAkH8AEcNAAsgASAAKAJ8Rwu/AQECfyABQQBKBEADQCAAIANBA3QgACADQQV0aiICKgIAIAIqAgQgAioCCCACKgIMIAIqAhAgAioCFCACLQAcuEQAAAAAAABgwKBEAAAAAAAAgD+itiACLQAduEQAAAAAAABgwKBEAAAAAAAAgD+itiACLQAeuEQAAAAAAABgwKBEAAAAAAAAgD+itiACLQAfuEQAAAAAAABgwKBEAAAAAAAAgD+itiACKAIYQQAQAyADQQFqIgMgAUcNAAsLQQALcgEEfyAAvCIEQf///wNxIQECQCAEQRd2Qf8BcSICRQ0AIAJB8ABNBEAgAUGAgIAEckHxACACa3YhAQwBCyACQY0BSwRAQYD4ASEDQQAhAQwBCyACQQp0QYCAB2shAwsgAyAEQRB2QYCAAnFyIAFBDXZyCw==`;

export async function parseSpxHeader(header: Uint8Array): Promise<SpxHeader> {
    const ui32s = new Uint32Array(header.buffer);
    const f32s = new Float32Array(header.buffer);
    const head = new SpxHeader();
    head.Fixed = String.fromCharCode(header[0]) + String.fromCharCode(header[1]) + String.fromCharCode(header[2]);
    head.Version = header[3];
    head.SplatCount = ui32s[1];
    head.MinX = f32s[2];
    head.MaxX = f32s[3];
    head.MinY = f32s[4];
    head.MaxY = f32s[5];
    head.MinZ = f32s[6];
    head.MaxZ = f32s[7];
    head.MinTopY = f32s[8];
    head.MaxTopY = f32s[9];
    head.CreateDate = ui32s[10];
    head.CreaterId = ui32s[11];
    head.ExclusiveId = ui32s[12];
    head.ShDegree = header[52];
    head.Flag1 = header[53];
    head.Flag2 = header[54];
    head.Flag3 = header[55];
    head.Reserve1 = ui32s[14];
    head.Reserve2 = ui32s[15];

    let comment: string = '';
    for (let i = 64; i < 124; i++) {
        comment += String.fromCharCode(header[i]);
    }
    head.Comment = comment.trim();

    head.HashCheck = true;
    if (head.Fixed !== 'spx') {
        return null;
    }

    // 哈希校验（检查模型是否由特定工具生成）
    const wasmBase64 = head.ExclusiveId ? WasmDataV3 : WasmOpen;
    const wasmModule = WebAssembly.compile(Uint8Array.from(atob(wasmBase64), c => c.charCodeAt(0)).buffer);
    const memory = new WebAssembly.Memory({ initial: 1, maximum: 1 });
    const instance = await WebAssembly.instantiate(await wasmModule, { env: { memory, expf } });
    const headerParser: any = instance.exports.H;

    const wasmMemory = new Uint8Array(memory.buffer);
    wasmMemory.set(header, 0);
    const code: number = headerParser(0);
    if (code) {
        head.HashCheck = false;
    }

    return head;
}

interface SpxBlockResult {
    splatCount: number;
    blockFormat: number;
    datas?: Uint8Array;
    isSplat?: boolean;
    isSh?: boolean;
    isSh1?: boolean;
    isSh2?: boolean;
    isSh3?: boolean;
    isSh23?: boolean;
    dataSh3?: Uint8Array;
    palettes?: Uint8Array;
    success: boolean;
}

export async function parseSpxBlockData(data: Uint8Array, header: SpxHeader = null): Promise<SpxBlockResult> {
    let ui32s = new Uint32Array(data.slice(0, 8).buffer);
    const splatCount = ui32s[0];
    const blockFormat = ui32s[1];
    const WebpBfs = [SpxBlockFormatData220, 300222];
    const isV3Webp = header?.Version >= 3 && WebpBfs.includes(blockFormat);

    if (blockFormat == SpxBlockFormatSH8) {
        const splatCount = 0;
        const palettes: Uint8Array = data.subarray(8);
        const success = true;
        return { splatCount, blockFormat, palettes, success };
    } else if (blockFormat == SpxBlockFormatSH9) {
        const { rgba } = await webpToRgba(data.subarray(8));
        const splatCount = 0;
        const palettes: Uint8Array = rgba;
        const success = true;
        return { splatCount, blockFormat, palettes, success };
    }

    let shDegree = header?.ShDegree || 0;
    if (blockFormat == SpxBlockFormatSH4) {
        if (header.ShDegree == SpxBlockFormatSH1) {
            const data1 = await sh123To1(data);
            return parseBlockData(splatCount, SpxBlockFormatSH1, data1, header.Version, shDegree);
        } else if (header.ShDegree == SpxBlockFormatSH2) {
            const data2 = await sh123To2(data);
            return parseBlockData(splatCount, SpxBlockFormatSH2, data2, header.Version, shDegree);
        } else if (header.ShDegree == SpxBlockFormatSH3) {
            const data2 = await sh123To2(data);
            const data3 = await sh123To3(data);
            const rs2 = await parseBlockData(splatCount, SpxBlockFormatSH2, data2, header.Version, shDegree);
            const rs3 = await parseBlockData(splatCount, SpxBlockFormatSH3, data3, header.Version, shDegree);
            rs2.success = rs2.success && rs3.success;
            rs2.isSh23 = true;
            rs2.dataSh3 = rs3.datas;
            return rs2;
        }
    }

    if (isV3Webp) {
        data = await decodeWebpBlockDatas(data);
    } else if (blockFormat == SpxBlockFormatData190) {
        data = await data190To19(data);
    } else if (blockFormat == SpxBlockFormatData10190) {
        data = await data10190To10019(data);
    }
    return parseBlockData(splatCount, blockFormat, data, header?.Version || 1, shDegree);
}

async function parseBlockData(splatCount: number, blockFormat: number, data: Uint8Array, spxVer: number, shDegree: number): Promise<SpxBlockResult> {
    const isSh1: boolean = SpxBlockFormatSH1 == blockFormat;
    const isSh2: boolean = SpxBlockFormatSH2 == blockFormat;
    const isSh3: boolean = SpxBlockFormatSH3 == blockFormat;
    const isSh: boolean = isSh1 || isSh2 || isSh3;
    const isSplat: boolean = !isSh;
    const wasms = [WasmOpen, WasmDataV1, WasmDataV2, WasmDataV3];
    const idx = blockFormat < 65536 ? 0 : spxVer;

    const resultByteLength = splatCount * (isSh ? SplatDataSize16 : SplatDataSize32);
    const wasmModule = WebAssembly.compile(Uint8Array.from(atob(wasms[idx]), c => c.charCodeAt(0)).buffer);
    const blockCnt: number = Math.ceil((resultByteLength + data.byteLength) / WasmBlockSize) + 1;
    const memory = new WebAssembly.Memory({ initial: blockCnt, maximum: blockCnt });
    const instance = await WebAssembly.instantiate(await wasmModule, { env: { memory, expf } });
    const dataParser: any = instance.exports.D;

    const wasmMemory = new Uint8Array(memory.buffer);
    wasmMemory.set(data, resultByteLength);
    const code = dataParser(0, resultByteLength, shDegree);
    if (code) return { splatCount, blockFormat, success: false };
    return { splatCount, blockFormat, success: true, datas: wasmMemory.slice(0, resultByteLength), isSplat, isSh, isSh1, isSh2, isSh3 };
}

export async function parseSplatToTexdata(data: Uint8Array, splatCount: number): Promise<Uint8Array> {
    const wasmModule = WebAssembly.compile(Uint8Array.from(atob(WasmOpen), c => c.charCodeAt(0)).buffer);
    const blockCnt = Math.ceil((splatCount * SplatDataSize32) / WasmBlockSize) + 1;
    const memory = new WebAssembly.Memory({ initial: blockCnt, maximum: blockCnt });
    const instance = await WebAssembly.instantiate(await wasmModule, { env: { memory, expf } });
    const dataParser: any = instance.exports.s;

    const wasmMemory = new Uint8Array(memory.buffer);
    wasmMemory.set(data.subarray(0, splatCount * SplatDataSize32), 0);
    const code: number = dataParser(0, splatCount);
    if (code) {
        console.error('splat data parser failed:', code);
        return new Uint8Array(0);
    }

    return wasmMemory.slice(0, splatCount * SplatDataSize32);
}

export async function parseWordToTexdata(x: number, y0z: number, isY: boolean = true, isNgativeY: boolean = true): Promise<Uint8Array> {
    const wasmModule = WebAssembly.compile(Uint8Array.from(atob(WasmDataV2), c => c.charCodeAt(0)).buffer);
    const memory = new WebAssembly.Memory({ initial: 1, maximum: 1 });
    const instance = await WebAssembly.instantiate(await wasmModule, { env: { memory, expf } });
    const dataSplat: any = instance.exports.w;

    const wasmMemory = new Uint8Array(memory.buffer);
    const f32s = new Float32Array(wasmMemory.buffer);
    const ngativeY = isNgativeY ? -1 : 1;
    f32s[0] = x;
    isY ? (f32s[1] = ngativeY * y0z) : (f32s[2] = ngativeY * y0z);
    dataSplat(0, isY ? 1 : 0);
    return wasmMemory.slice(0, SplatDataSize32);
}

function expf(v: number) {
    return Math.exp(v);
}
